### ISSUE TITLE
Fails with DW 2022-07-31a "Igor" because of a breaking change.

### ISSUE THREAD

**Issue by einhirn** [msakuta/SketchCanvas#6]
DokuWiki version: Release 2022-07-31a "Igor"
has a breaking change that impacts this plugin, because the EDIT_FORM_ADDTEXTAREA event isn't implemented here yet.

This results in this Plugin not working anymore and an error message "No editor for edit target plugin_sketchcanvas found."

Further reference:
https://www.dokuwiki.org/devel:releases:refactor2021
https://www.dokuwiki.org/devel:event:edit_form_addtextarea

It seems your plugin should contain both the old and the new way of doing things for now, dropping support for old DW versions after a while...

**Comment by Floffyko** [comment]
"No editor for edit target plugin_sketchcanvas found."
The same here.

**Comment by msakuta** [comment]
Thank you for reporting. I will look into it.

**Comment by msakuta** [comment]
Ok, after a little research, I found out that it can't be fixed as easily as renaming the event handler. The DW team completely changed the way a form is handled, and they also failed to detect my plugin in [the list of plugins that uses old events](https://docs.google.com/spreadsheets/d/193e-wrgej6DGqKQxcsghEbMR4OmQtDUmnmp9cfjF07o/edit#gid=0), so they managed to give me a surprise present after 2 years.

My previous method with plain HTML and JavaScript text injection wouldn't work anymore with the new OOP interface. I'm not sure if there is a good workaround. It may take some time to research and find a solution, so please be patient or if you have an idea a PR is appreciated.

**Comment by Floffyko** [comment]
Still interested and still waiting for some successes :-) Any ?

**Comment by msakuta** [comment]
Sorry I really appreciate someone is still interested in this project, but the issue is not so easy to solve unless I sit down and devote some time on it. In the meantime I have been distracted by other projects :)

I can't promise when but I will revisit with more commitment when I can allocate such time.

**Comment by Floffyko** [comment]
Reminder, Please support this plugin inf you have a little time. I still consider this plugin very useful. I have some diagrams draw with it but it cannot be read them over an year ago. I am still on DW version "Hogfathe" for the sake of better compatibility with other plugins.
It needs first to be solved the following error:
startSectionEdit: $data "plugin_sketchcanvas" is NOT an array! One of your plugins needs an update.
Thanks a lot.

**Comment by msakuta** [comment]
I think I managed to fix it by PR #7. I tested on both new and old distributions so it should work on any user.

It turned out, the fix was not that complicated, but to find out how to do it wasn't trivial. Basically they refactored the whole Form class to make their implementation easier. I can understand that, but I'm not supportive of dropping backwards compatibility so casually without little guide to migrate (there is [this little page](https://www.dokuwiki.org/devel:form) about the new Form which wasn't very helpful). It's still my (plugin developer's) responsibility to keep backwards compatibility, so I need to keep both old and new event handlers for a while.

Okay, enough ranting. Thank you for your patiance. I will make a new version.

**Comment by Floffyko** [comment]
Nice work, thank you. For a useful plugin we will have always patience :-).  So after your last version, in 2018-04-22b "Greebo" the plugin is working, but on my  Release 2020-07-29 "Hogfather", my most used version, is not working, it does not show the generated image, with no extra error explanation. So, maybe it could be a plugin incompatibility?

**Comment by msakuta** [comment]
Hmm, interesting. I thought I tested all of Greebo, Hogfather, Igor and Jack Jackrum, but when I checked again, only Hogfather didn't work. Let me check it out.

You are a very good tester 😅

**Comment by msakuta** [comment]
Hmm, it seems my issue was a cache. When I enter edit mode it showed, and saving the page with a little edit fixed the issue.
I also tried to install Hogfather from scratch and overwrite data folder from backup. It also worked.

Can you provide with more details? For example, platform, the method to migrate from old version, and whether entering edit mode helps?

**Comment by Floffyko** [comment]
Yes, the things seems to work again :-) Thanks. Please verify: the following plugins, I think they are incompatible:  ApexCharts Plugin and CodeMirror plugin. In my case these 2 plugins made invisible and nonfunctional the plugin.

**Comment by msakuta** [comment]
Can you make a new issue for that? It sounds like a different symptom, and having a separate issue will make it easier to find for other users.
