### ISSUE TITLE
ApexCharts  and CodeMirror are they incompatible?

### ISSUE THREAD

**Issue by Floffyko** [msakuta/SketchCanvas#8]
Please verify the following plugins while it seems they are incompatible: ApexCharts  and CodeMirror. In my case (2020-07-29 "Hogfather") these 2 plugins made invisible or nonfunctional the SketchCanvas plugin. Thanks

**Comment by msakuta** [comment]
Thanks for reporting! I could reproduce the problem with [ApexCharts](https://www.dokuwiki.org/plugin:achart?s[]=apexcharts) but not with [CodeMirror](https://www.dokuwiki.org/plugin:codemirror?s[]=codemirror). ApexCharts and SketchCanvas at the same time shows this error in JS console and nothing renders in the canvas.

```
Error: Function yaml.safeLoad is removed in js-yaml 4. Use yaml.load instead, which is now safe by default.
    at Object.safeLoad (js.php?t=dokuwiki&tseed=06b6e5a70b4f081b91b62a4a9d80df6f:1:131445)
    at SketchCanvas.loadData (SketchCanvas.js:1242:30)
    at HTMLDocument.<anonymous> (doku.php?id=javascript:37:22)
```

I think I can investigate with this about ApexCharts, but I don't see a problem with CodeMirror.

**Comment by msakuta** [comment]
Ok, I found the issue with CodeMirror. It's a different reason from ApexCharts incompatibility.

# Symptom

If you enable SketchCanvas and CodeMirror at the same time, you could see the figure, but cannot edit it with graphical editor. If you edit with graphical editor and press save, it won't reflect to the wiki source and be silently lost.

# Cause

CodeMirror replaces the text area element with a custom one. It is not full fledged WYSIWYG editor, but it's enough to break SketchCanvas.

SketchCanvas replaces the contents of the default text area element (with id=`wiki__text`), but CodeMirror replaces the textarea with its custom one, so the contents from SketchCanvas cannot be reflected to the text.

Below shows element inspector highlighting a DOM element in the CodeMirror editor.

![image](https://github.com/msakuta/SketchCanvas/assets/2798715/345fe0e6-2ec0-40eb-998c-c0b4ec85f694)

And this is the inspector without CodeMirror.

![image](https://github.com/msakuta/SketchCanvas/assets/2798715/856ec9c3-2a0a-4614-8ad6-46c939fce6da)


# Solution

Unfortunately I don't have a really good idea to fix it. Since SketchCanvas editor allows bidirectional edits between the text area and the graphical editor, we need to use the default textarea, and any other plugin can play with it however they like.

One workaround I've found is to use Native DokuWiki editor from CodeMirror's config button to temporarily disable text highlighting. It is not perfect since you need to switch it every time you edit a text or SketchCanvas text, but at least it works.

![image](https://github.com/msakuta/SketchCanvas/assets/2798715/230d23e4-6986-4c3c-9180-8247fc319f87)
